import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const dist = path.resolve("dist");
const out = path.resolve("desktop/generated-assets.ts");

const files: string[] = [];
const walk = (dir: string) => {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name);
    if (statSync(p).isDirectory()) {
      walk(p);
    } else {
      files.push(p);
    }
  }
};

if (!statSync(dist, { throwIfNoEntry: false })?.isDirectory()) {
  console.error(`dist/ not found. Run "bun run build" first.`);
  process.exit(1);
}

walk(dist);
files.sort();

const entries = files
  .map((f) => {
    const key = path.relative(dist, f).split(path.sep).join("/");
    return `  ${JSON.stringify(key)}: ${JSON.stringify(readFileSync(f, "utf8"))},`;
  })
  .join("\n");

mkdirSync(path.dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Auto-generated by scripts/embed-assets.ts — do not edit by hand.\n// Embedded contents of dist/ so the desktop executable is self-contained.\nexport const assets: Record<string, string> = {\n${entries}\n};\n`
);

console.log(`Embedded ${files.length} asset(s) from dist/ into ${out}`);
